# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'last.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form0(object):
    def setupUi(self, Form0):
        Form0.setObjectName("Form0")
        Form0.resize(293, 190)
        Form0.setMaximumSize(QtCore.QSize(293, 190))
        self.label_2 = QtWidgets.QLabel(Form0)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 41, 23))
        self.label_2.setObjectName("label_2")
        self.dis = QtWidgets.QLabel(Form0)
        self.dis.setGeometry(QtCore.QRect(130, 70, 41, 23))
        self.dis.setObjectName("dis")
        self.stu_no = QtWidgets.QLineEdit(Form0)
        self.stu_no.setGeometry(QtCore.QRect(80, 30, 91, 23))
        self.stu_no.setText("")
        self.stu_no.setObjectName("stu_no")
        self.pbar = QtWidgets.QProgressBar(Form0)
        self.pbar.setGeometry(QtCore.QRect(80, 70, 171, 23))
        self.pbar.setProperty("value", 0)
        self.pbar.setObjectName("pbar")
        self.query = QtWidgets.QPushButton(Form0)
        self.query.setGeometry(QtCore.QRect(180, 30, 71, 23))
        self.query.setObjectName("query")
        self.label = QtWidgets.QLabel(Form0)
        self.label.setGeometry(QtCore.QRect(40, 30, 41, 23))
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(Form0)
        self.label_4.setGeometry(QtCore.QRect(40, 110, 54, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form0)
        self.label_5.setGeometry(QtCore.QRect(40, 150, 54, 21))
        self.label_5.setObjectName("label_5")
        self.run_days = QtWidgets.QSpinBox(Form0)
        self.run_days.setGeometry(QtCore.QRect(100, 150, 42, 22))
        self.run_days.setObjectName("run_days")
        self.runrun = QtWidgets.QPushButton(Form0)
        self.runrun.setGeometry(QtCore.QRect(160, 150, 75, 23))
        self.runrun.setObjectName("runrun")
        self.stime = QtWidgets.QDateTimeEdit(Form0)
        self.stime.setGeometry(QtCore.QRect(100, 110, 91, 22))
        self.stime.setDateTime(QtCore.QDateTime(QtCore.QDate(2022, 3, 5), QtCore.QTime(18, 31, 12)))
        self.stime.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2099, 12, 31), QtCore.QTime(23, 59, 59)))
        self.stime.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2021, 9, 14), QtCore.QTime(0, 0, 0)))
        self.stime.setCalendarPopup(True)
        self.stime.setObjectName("stime")
        self.pbar.raise_()
        self.label_2.raise_()
        self.dis.raise_()
        self.stu_no.raise_()
        self.query.raise_()
        self.label.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.run_days.raise_()
        self.runrun.raise_()
        self.stime.raise_()

        self.retranslateUi(Form0)
        QtCore.QMetaObject.connectSlotsByName(Form0)

    def retranslateUi(self, Form0):
        _translate = QtCore.QCoreApplication.translate
        Form0.setWindowTitle(_translate("Form0", "无情的跑步机器"))
        self.label_2.setText(_translate("Form0", "公里数"))
        self.dis.setText(_translate("Form0", "-km"))
        self.query.setText(_translate("Form0", "查询"))
        self.label.setText(_translate("Form0", "学号"))
        self.label_4.setText(_translate("Form0", "开始日期"))
        self.label_5.setText(_translate("Form0", "跑步天数"))
        self.runrun.setText(_translate("Form0", "校园网跑步"))
        self.stime.setDisplayFormat(_translate("Form0", "yyyy/M/d"))
