# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_run.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(309, 107)
        Form.setMaximumSize(QtCore.QSize(309, 107))
        Form.setAutoFillBackground(False)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 61, 23))
        self.label_2.setObjectName("label_2")
        self.query = QtWidgets.QPushButton(Form)
        self.query.setGeometry(QtCore.QRect(210, 10, 75, 23))
        self.query.setObjectName("query")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(100, 40, 81, 23))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 10, 31, 23))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(60, 10, 113, 23))
        self.lineEdit.setObjectName("lineEdit")
        self.runrun = QtWidgets.QPushButton(Form)
        self.runrun.setGeometry(QtCore.QRect(210, 40, 75, 23))
        self.runrun.setObjectName("runrun")
        self.dele = QtWidgets.QPushButton(Form)
        self.dele.setGeometry(QtCore.QRect(210, 70, 75, 23))
        self.dele.setObjectName("dele")
        self.progressBar1 = QtWidgets.QProgressBar(Form)
        self.progressBar1.setGeometry(QtCore.QRect(20, 70, 181, 23))
        self.progressBar1.setProperty("value", 0)
        self.progressBar1.setObjectName("progressBar1")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "已跑公里数"))
        self.query.setText(_translate("Form", "查询"))
        self.label_3.setText(_translate("Form", "120km"))
        self.label.setText(_translate("Form", "学号"))
        self.runrun.setText(_translate("Form", "一键跑步"))
        self.dele.setText(_translate("Form", "一键清除"))
